mjpeg:
  host: '0.0.0.0'
  port: 5052

streams:
  is_use: False
  stream_list: '
Camera_0,rtsp://172.28.182.204:80/live/camera_1
Camera_1,rtsp://172.28.182.204:80/live/camera_5
Camera_2,rtsp://172.28.182.204:80/live/camera_10
Camera_3,rtsp://172.28.182.204:80/live/camera_15
Camera_4,rtsp://172.28.182.204:80/live/camera_20
'

#app:
#  logfile: 'mjpeg.log'
